apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - mountPath: /cache
          name: cache-vol
      volumes:
      - name: cache-vol
        emptyDir:
          sizeLimit: 500Mi  
